package models

import "time"

// Application represents the structure for an application in the database and API.
type Application struct {
	// ID is the unique identifier for the application, automatically generated by MongoDB.
	// `bson:"_id,omitempty"` ensures MongoDB's default `_id` field is used and is optional for insert.
	// `json:"id"` maps it to `id` in JSON responses.
	ID         interface{} `json:"id" bson:"_id,omitempty"`
	Name       string      `json:"name" bson:"name"`
	Role       string      `json:"role" bson:"role"`
	ResumePath string      `json:"resumePath" bson:"resumePath"`
	CreatedAt  time.Time   `json:"createdAt" bson:"createdAt"`
}
